### ISSUE TITLE
Text align for <ul> or <ol> tag is not working

### ISSUE THREAD

**Issue by junan-trustarc** [KillerCodeMonkey/ngx-quill-example#1749]
![image](https://github.com/KillerCodeMonkey/ngx-quill-example/assets/134445960/7849ccbc-2d69-400a-a6af-3cbbeff7b865)

**li** tag should have **ql-align-center** class when align is changed to **ol** or **li**, either center, right, justify.

When those HTML snippet is injected to innerHTML on div, only **li** and **ol** tag doesn't work with align.
Could you please look and fix, 
Thanks !

**Comment by KillerCodeMonkey** [comment]
I think this is a quilljs issue.

**Comment by KillerCodeMonkey** [comment]
And keep in mind there are known clitshes when browser extensions used like grammarly

**Comment by junan-trustarc** [comment]
ah..... yeah.. I can see issue on quill 2.0.1, I tried to use native quill 1.3.7, seems good

**Comment by kulitha** [comment]
Hey @KillerCodeMonkey I didn't create an issue for this since I'm not sure if it's a quill problem, but bullet points for `<ul>` and numbers for `<ol>` are not displayed in the quill-container with relevant CSS using `innerHTML`, or using `<quill-view-html></quill-view-html>`.

This can be seen in the above screenshots and is happening in the live demo as well.
![image](https://github.com/KillerCodeMonkey/ngx-quill-example/assets/33679434/eb5873c3-2444-466c-a121-c61e7882a68c)


Is there a fix for this?

**Comment by KillerCodeMonkey** [comment]
Thats a quill thing. There is now a method to get Editors HTML from the editor and I am using this now internally.

If I would not use it other issues will appear. 


Am 18. Juni 2024 17:14:36 MESZ schrieb kulitha ***@***.***>:

**Comment by KillerCodeMonkey** [comment]
https://github.com/slab/quill/issues/4124

There are some more detailed explanations.

**Comment by kulitha** [comment]
Thank you very much for the reply.
