### ISSUE TITLE
SSR document is not defined error

### ISSUE THREAD

**Issue by idonov** [KillerCodeMonkey/ngx-quill-example#617]
I am trying to create and register some custom modules and I  keep getting "document is not defined" error from the server.
Using angular universal, angular 11, ngx-quill 13

I am importing Quill in to the component., and the variable assignment line is producing the error.

```
import * as QuillNamespace from 'quill';
// let Quill: any = QuillNamespace; <------ this errors on the server
```

**Comment by KillerCodeMonkey** [comment]
quilljs is not ssr ready, because it directly access the `document` property, which does not exist on serverside.

what you can try is to pass those custom modules custom options directly to ngx-quill:
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/f60296ca4ac5c8bbbc2b4f04f150a24d21b38e84/src/app/app.module.ts

or you need to mock the document object on server side like described here:
https://github.com/KillerCodeMonkey/ngx-quill#ngx-quill-v9
