### ISSUE TITLE
mat-quill not accepting module input

### ISSUE THREAD

**Issue by NewToStuff** [KillerCodeMonkey/ngx-quill-example#673]
Hi,

I have reached a difficulty in integrating<mat-quill> into my application as a custom form control.  

I am basing the integration on the custom-toolbar example. Its probably a Newbie mistake but when trying to bind to the modules input using the code below the modules input is not found.

`
    <mat-quill
      customToolbarPosition="bottom"
      [(ngModel)]="editorModel"
      format="object"
      [modules]="{ counter: { container: '#mat-quill-counter', unit: 'word' } }"
      >
`
The error I receive is:

If 'mat-quill' is an Angular component and it has 'modules' input, then verify that it is part of this module.

If I remove the [modules] binding then the error is no longer generated. Does anyone know whether there is anything in particular I should be verifying.

Thanks.

Paul

**Comment by KillerCodeMonkey** [comment]
Just Check of the mat-quill component has The Modules input. If Not Just
add IT and adapt what The ngx-quill quill Component does


Am 11.04.2021 in 13:52, NewToStuff ***@***.***> schrieb:

Hi,

I have reached a difficulty in integrating into my application as a custom
form control.

I am basing the integration on the custom-toolbar example. Its probably a
Newbie mistake but when trying to bind to the modules input using the code
below the modules input is not found.

<mat-quill customToolbarPosition="bottom" [(ngModel)]="editorModel"
format="object" [modules]="{ counter: { container: '#mat-quill-counter',
unit: 'word' } }" >
The error I receive is:

If 'mat-quill' is an Angular component and it has 'modules' input, then
verify that it is part of this module.

If I remove the [modules] binding then the error is no longer generated.
Does anyone know whether there is anything in particular I should be
verifying.

Thanks.

Paul

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill-example/issues/673>, or
unsubscribe

**Comment by NewToStuff** [comment]
Hi,

Thanks for your swift reply:

I don't think it has the "modules" input but I am still confused.

Mat-quill is basically list from your example here without intentional modification. I cannot see where the modules input is defined in your example which runs fine - I suspect I have broken copying through its implementation.

https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/mat-quill/mat-quill.ts


Thanks in advance.
