### ISSUE TITLE
Extract mat-quill to a separate npm package

### ISSUE THREAD

**Issue by Maximaximum** [KillerCodeMonkey/ngx-quill-example#698]
Even though there's a lot of examples that use the `mat-quill` component, it's not easily accessible for use in other projects. Anyone who wants to use the mat-quill component has to copy-paste the code from `mat-quill-base.ts`, `mat-quill.ts`, `mat-quill.module.ts` into their own project. But even then, due to code complexity, the developer will face multiple issues like #673 and #421.

Seems like using `quill` in angular+material environment is quite a popular scenario, so a lot of people would benefit from having a separate component just works out of the box, just like the examples do.

There's also an npm package whose name implies that it would do exactly that, but it seems to be just a clone of the original package without any changes: https://www.npmjs.com/package/ngx-quill-material

Thanks a lot for your work!

**Comment by KillerCodeMonkey** [comment]
since i have to maintain it, i will not add an additional component for material ui ;-).

it will increase the complexity of the project and the workload, because i do not only have to catch up all changes for quill or angular. I need to be up to date for material ui, too. Additional i would introduce a maybe blocking peer dependencies between angular and material ui, where i am - in the worst case -  not able to directly support new angular versions.

So i could create a custom repo for ngx-quill-material, but then i have to maintain it, and i am personally do not like how things are done in material ui for angular and i do not have much experiences in using it.

**Comment by Maximaximum** [comment]
Thanks for your reply, @KillerCodeMonkey. Fair enough!

Would you mind then to at least update your examples with one that would show how all the existing `ngx-quill` features could be augmented with material features?

This would not require you to maintain the example and keep it updated with regards to any `@angular/material` changes. But it will make it clear for people how to add material features without losing the core `ngx-quill` features.

Currently, I'm struggling to combine them. I've copied and pasted your material example, and the angular material functionality does work. However, the `@Input`s like `modules` don't work out of the box. I've copied all the `@Input`s defined on `QuillEditorBase` to `MatQuill`, and they seem to work. But now the validation doesn't work. 

I've tried to add
```typescript
    {
      multi: true,
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => MatQuill),
    },
    {
      multi: true,
      provide: NG_VALIDATORS,
      useExisting: forwardRef(() => MatQuill),
    },
```

to `MatQuill`'s `providers`, but it gives a `Circular dependency in DI detected for MatQuill` error at runtime.

Could you please give me a hint on how to overcome this issue?
